[workspace]
resolver = "2"
members = [
    "crates/wf-proxy",
    "crates/wf-core",
    "crates/wf-packet",
    "crates/wf-tui",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["darkstardevx <darkstardevx@gmail.com>"]
license = "MIT"

[package]
name = "wraithflow"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wf-proxy = { path = "crates/wf-proxy" }
wf-core = { path = "crates/wf-core" }
wf-packet = { path = "crates/wf-packet" }
tokio = { version = "1.38", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
